{% set name = "zstandard" %}
{% set version = "0.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22395e97bcfdb222246da4fdf8739ed762ffce1e5d0b526eb051c90da20268d7
  patches:
    - 0001-Use-compiler-from-environment.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cffi >=1.8
  run:
    - python
    - cffi >=1.8

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - zstandard

about:
  home: https://github.com/indygreg/python-zstandard
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard bindings for Python
  description: |
    This project provides Python bindings for interfacing with the
    Zstandard compression library. A C extension and CFFI interface are
    provided.
  doc_url: https://github.com/indygreg/python-zstandard/blob/master/README.rst#python-zstandard
  dev_url: https://github.com/indygreg/python-zstandard

extra:
  recipe-maintainers:
    - rmax
    - xhochy
