{% set name = "zstandard" %}
{% set version = "0.10.2" %}
{% set sha256hash = "86c9dee0fe6d4ea5bf394767929fdf5f924d161d9a6d23adcd58a690c5e160b0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256hash }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cffi >=1.11
  run:
    - python

about:
  home: https://github.com/indygreg/python-zstandard
  license: BSD 3-Clause
  summary: "Zstandard bindings for Python"
  description: |
    This project provides Python bindings for interfacing with the
    Zstandard compression library. A C extension and CFFI interface are
    provided.
  doc_url: https://github.com/indygreg/python-zstandard/blob/master/README.rst#python-zstandard
  dev_url: https://github.com/indygreg/python-zstandard

extra:
  recipe-maintainers:
    - rmax
    - jcrist
