schema_version: 1

context:
  name: zstandard
  version: 0.25.0
  zstd_version: 1.5.7

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 7713e1179d162cf5c7906da876ec2ccb9c3a9dcbdffef0cc7f70c3667a205f0b

build:
  number: 0

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: cffi
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cffi >=1.11
    - zstd 1.5.7.*
    - packaging
  run:
    - python
    - cffi >=1.11
    # The Python bindings use private APIs and are tightly coupled to zstd
    # https://github.com/indygreg/python-zstandard/blob/0063333790a853360c816101511635865405834f/c-ext/backend_c.c#L149
    - ${{ pin_compatible("zstd", upper_bound="x.x.x") }}

tests:
  - python:
      imports:
        - zstandard
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - zstd/LICENSE
  summary: Zstandard bindings for Python
  description: |
    This project provides Python bindings for interfacing with the
    Zstandard compression library. A C extension and CFFI interface are
    provided.
  homepage: https://github.com/indygreg/python-zstandard
  repository: https://github.com/indygreg/python-zstandard
  documentation: https://github.com/indygreg/python-zstandard/blob/master/README.rst#python-zstandard

extra:
  recipe-maintainers:
    - rmax
    - xhochy
    - pavelzw
